apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webchat-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webchat-deployment
  # edit min and max replicas to match with the cluster
  # keep in mind that one pod is reserved for redis, so maxReplicas should be one less than cluster max
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
